### PR TITLE
Add support for digests detected from ECC certificates

### PR DESCRIPTION
**Pull request by minfrin**
Previously, the digest could be detected on RSA certificates only. This
patch adds detection for ECC certificates.

Fixes https://github.com/net-snmp/net-snmp/issues/258

### CODE REVIEW

**Comment by bvanassche** [comment]
A modified version of this patch has been applied as commit a1968db524e087a36a19a351b89bf6f1633819aa. Please take a look.

**Comment by minfrin** [comment]
Perfect, thank you for this.

**Comment by minfrin** [comment]
Would it be possible to backport this to the 5.9.1 stable branch?

**Comment by bvanassche** [comment]
Please take a look at commit 5b9515d0c728.

**Comment by minfrin** [comment]
I've not had any luck producing a backport PR, the best git will give me is a PR with over a thousand commits in it, which leaves me little confidence I'm doing this correctly. My hatred for git knows no bounds.

**Comment by minfrin** [comment]
Blew it all away and tried again, managed to come up with https://github.com/net-snmp/net-snmp/pull/387 - can you take a look?

**Comment by bvanassche** [comment]
I haven't found any commits in that pull request that are not yet upstream. Please try the following:
~~~
git checkout origin/V5-9-patches -b V5-9-patches
[ edit source files ]
git commit -a
git push minfrin +V5-9-patches
~~~
and create a pull request from https://github.com/minfrin/net-snmp/tree/V5-9-patches.

**Pull request closed without merging**
