### PR TITLE
Change checks for libnl to make sure it fails for missing pkg-config

### PR DESCRIPTION
**Pull request by nielsb**
as well as missing libnl3 modules.

### CODE REVIEW

**Comment by bvanassche** [comment]
This patch makes the Android build fail. Apparently Android has the libnl library but doesn't have a /usr/lib/.../pkgconfig/libnl-3.0.pc. Can you fix this or do you perhaps expect me to look into this?

**Comment by nielsb** [comment]
Yes, I noticed, and was wondering if some devel package maybe was missing. ANd then I thought about skippingh the tests for libnl when EtherLike-MIB was not requested.
I have never touched an Android build platform, so if you could give it a look, I would be grateful.

**Comment by bvanassche** [comment]
In case anyone else would want to look into this, Net-SNMP can be cross-compiled for Android as follows:
```
sudo MODE=Android ci/install.sh
MODE=Android ci/build.sh
```

**Comment by nielsb** [comment]
Hmm, just tried that, with CentOS7 as the host. This configures OK, but failed with
```
libtool: compile:  aarch64-linux-android34-clang -I../include -I. -I../snmplib -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -Ulinux -Dlinux=linux -Wall -Wextra -Wstrict-prototypes -Wwrite-strings -Wcast-qual -Wundef -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -Wcast-function-type -Wredundant-decls -c snmpksm.c  -fPIC -DPIC -o .libs/snmpksm.o
snmpksm.c:48:10: fatal error: 'krb5.h' file not found
#include <krb5.h>
```
When I compile normally this has no problems with snmpksm ...

**Comment by bvanassche** [comment]
> Hmm, just tried that, with CentOS7 as the host. This configures OK, but failed with
> 
> ```
> libtool: compile:  aarch64-linux-android34-clang -I../include -I. -I../snmplib -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -Ulinux -Dlinux=linux -Wall -Wextra -Wstrict-prototypes -Wwrite-strings -Wcast-qual -Wundef -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -Wcast-function-type -Wredundant-decls -c snmpksm.c  -fPIC -DPIC -o .libs/snmpksm.o
> snmpksm.c:48:10: fatal error: 'krb5.h' file not found
> #include <krb5.h>
> ```
> 
> When I compile normally this has no problems with snmpksm ...

That's a surprise to me. Before I shared the above instructions, I verified on an Ubuntu system that these instructions work fine.

**Comment by bvanassche** [comment]
Is commit 771966122e2fa7beca54febdd223464676c72fd3 sufficient to close this pull request?

**Comment by nielsb** [comment]
First of all, it would of course be best to detect this at contifgure time, but it would work.
It also needs a check for libnl-route-3-dev (Ubuntu, Debian). Check for HAVE_NETLINK_ROUTE_LINK_H,
and maybe a check for pkg-config, as that could be the reason for not detecting libnl3-devel.

**Pull request closed without merging**
