### PR TITLE
Add gitattributes file to use eol=lf for almost all files

### PR DESCRIPTION
**Pull request by orgads**
This fixes autoreconf on MSYS2 and possibly other issues.

### CODE REVIEW

**Comment by bvanassche** [comment]
eol=lf applies to all Net-SNMP source files except the unmaintained win32/.../*.ds[pw] files. Shouldn't eol=lf be applied to all Net-SNMP source files?

**Comment by orgads** [comment]
I tried to keep the attributes for minimal. Source files don't have to be lf. If you prefer, I can change it to *, and exclude ds[pw] files.

**Comment by orgads** [comment]
> eol=lf applies to all Net-SNMP source files except the unmaintained win32/.../*.ds[pw] files. Shouldn't eol=lf be applied to all Net-SNMP source files?

Done

**Comment by bvanassche** [comment]
Thanks for the patch!

**Pull request merged**
