### PR TITLE
mibgroup: fix NULL dereference in write_snmpNotifyFilterProfileRowStatus()

### PR DESCRIPTION
**Pull request by ProjectMutilation**
In case RESERVE_1 pointer var_val was checked against NULL, although it was dereferenced for assignment set_value before check
Found by RASU JSC

### CODE REVIEW

**Comment by hardaker** [comment]
As is, this writes a code block into the middle of variable declarations.  Although some newer C compilers allow for this, we still target ones that may not -- thus the code must go below all variable definitions.

**Comment by ProjectMutilation** [comment]
@hardaker okay, If you agree with the need for a patch and there are no other comments, I will correct for compliance.

Thanks for the feedback

**Comment by bvanassche** [comment]
I'm not sure this patch is the right approach to suppress the static analyzer warning. Shouldn't the caller guarantee that var_val != NULL? If so, a better fix would be to remove the var_val != NULL checks instead of adding another such check.

**Comment by bvanassche** [comment]
> > I'm not sure this patch is the right approach to suppress the static analyzer warning. Shouldn't the caller guarantee that var_val != NULL? If so, a better fix would be to remove the var_val != NULL checks instead of adding another such check.
> 
> I agree that it's probably just an unnecessary check, but is it for sure?

My conclusion from a review from the code in the snmplib/ directory is that either var_val != NULL && var_len != 0 or that var_val == NULL && var_len == 0.

**Comment by ProjectMutilation** [comment]
> > > I'm not sure this patch is the right approach to suppress the static analyzer warning. Shouldn't the caller guarantee that var_val != NULL? If so, a better fix would be to remove the var_val != NULL checks instead of adding another such check.
> > 
> > 
> > I agree that it's probably just an unnecessary check, but is it for sure?
> 
> My conclusion from a review from the code in the snmplib/ directory is that either var_val != NULL && var_len != 0 or that var_val == NULL && var_len == 0.

okay, then PR is unnecessary and can be closed

**Pull request closed without merging**
