### PR TITLE
Added fix for TSM/TLS segfault.

### PR DESCRIPTION
**Pull request by florian-koehler**
The function `SSL_CTX_add_extra_chain_cert` frees the used X509 pointer after destroying the associated SSL_CTX according to https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_add_extra_chain_cert.html. This leads to the X509 pointer from the cert-map being freed, while still being potentially used in further sessions. This problem regularly occurs, when repeatedly opening and closing netsnmp-sessions in a TSM/TLS-configuration.

I added a fix, where I create a copy of the original X509 pointer using `X509_dup`, which is used in `SSL_CTX_add_extra_chain_cert` instead of the cached X509 pointer and autonomously cleaned up by openssl after destroying the SSL_CTX.

### CODE REVIEW

**Comment by florian-koehler** [comment]
Added issue for PR (#516)

**Comment by bvanassche** [comment]
Please rebase your branch such that the merge commit disappears (git pull --rebase && git push ... +tsm_mem_hotfix).

**Comment by florian-koehler** [comment]
Rebased and pushed updated repo to my remote branch.

**Comment by bvanassche** [comment]
Hmm ... I still see "Merge branch 'tsm_mem_hotfix' of ..."?

**Pull request closed without merging**
