### PR TITLE
V5 9 patches

### PR DESCRIPTION
**Pull request by nielsb**
Two commits that both remove a bunch of warnings!
I hope to soon have reached the bottom of these :-)

### CODE REVIEW

**Comment by hardaker** [comment]
So I actually disagree with the ; removal.  We didn't have them for a long time, but they help code-editors that don't understand macros, eg.  So we intentionally started adding ;s at some point to some calls like that.  I suspect we're not using them everywhere though already?  hmmmmm.....  1284 without and 44 with.  I guess that wins the battle.

**Comment by nielsb** [comment]
And clang complaining about it now, probably means that gcc will start complaining in the not too far future :-(

**Comment by bvanassche** [comment]
I'm in favor of terminating all config macro invocations with a semicolon. How about suppressing the clang warnings with a patch like the one below?
```
diff --git a/configure.d/config_modules_agent b/configure.d/config_modules_agent
index a06eaed125b5..03e445332abb 100644
--- a/configure.d/config_modules_agent
+++ b/configure.d/config_modules_agent
@@ -192,7 +192,7 @@ while test "x$new_module_list" != "x"; do
     #     - mib_module   => libnetsnmpmibs   (default)
     #     - agent_module => libnetsnmpagent
     #
-    AH_TOP([#define config_belongs_in(x)])
+    AH_TOP([#define config_belongs_in(x) extern void this_function_is_not_used(void)])
     module_type=mib_module
     if test -f $srcdir/$mibdir/$i.h; then
       changequote(, )
@@ -277,7 +277,7 @@ while test "x$new_module_list" != "x"; do
       	#
         # check if $i has any conflicts
         #
-        AH_TOP([#define config_exclude(x)])
+        AH_TOP([#define config_exclude(x) extern void this_function_is_not_used(void)])
         new_list_excl=`$MODULECPP module_tmp_header.h | \
                        $SED -n 's/.*config_exclude(\(.*\)).*/\1/p'`
 	if test "x$new_list_excl" != "x"; then
@@ -306,7 +306,7 @@ while test "x$new_module_list" != "x"; do
         #
         # check if $i has any architecture specific requirements
         #
-        AH_TOP([#define config_arch_require(x,y)])
+        AH_TOP([#define config_arch_require(x,y) extern void this_function_is_not_used(void)])
         changequote(, )
         new_list_arch=`$MODULECPP module_tmp_header.h | \
                        $SED -n 's/.*config_arch_require( *\([^ ]*\) *, *\([^ ]*\) *).*/\1-xarchx-\2/p'`
@@ -328,7 +328,7 @@ while test "x$new_module_list" != "x"; do
       	# macro: config_version_require((base, version, version-modules, ...))
       	#  - lists alternative modules used from different versions.
         #
-        AH_TOP([#define config_version_require(x)])
+        AH_TOP([#define config_version_require(x) extern void this_function_is_not_used(void)])
         [new_list_alt3=`$MODULECPP module_tmp_header.h | \
             $AWK '
                 BEGIN {
@@ -370,7 +370,7 @@ while test "x$new_module_list" != "x"; do
         #
         # check if $i has any other required modules
         #
-        AH_TOP([#define config_require(x)])
+        AH_TOP([#define config_require(x) extern void this_function_is_not_used(void)])
         new_list="$new_list `$MODULECPP module_tmp_header.h | \
                   $SED -n 's/.*config_require(\(.*\)).*/\1/p'`"
         AC_MSG_MODULE_DBG(" $i will test: $new_list")
@@ -407,7 +407,7 @@ while test "x$new_module_list" != "x"; do
         #
         # check if $i has any mibs to add
         #
-        AH_TOP([#define config_add_mib(x)])
+        AH_TOP([#define config_add_mib(x) extern void this_function_is_not_used(void)])
         new_mibs=`$MODULECPP module_tmp_header.h | \
                   $SED -n 's/.*config_add_mib(\(.*\)).*/\1/p'`
 	if test "x$new_mibs" != "x"; then
@@ -454,7 +454,7 @@ while test "x$new_module_list" != "x"; do
         # check for config_parse_dot_conf
         #  (generally not used any longer; old auto-load a .conf token)
         #
-        AH_TOP([#define config_parse_dot_conf(w,x,y,z)])
+        AH_TOP([#define config_parse_dot_conf(w,x,y,z) extern void this_function_is_not_used(void)])
         changequote(, )
         $MODULECPP module_tmp_header.h | \
         $SED -n 's@.*config_parse_dot_conf(\([^)]*\), *\([^),]*\), *\([^),]*\), *\([^),]*\)).*@register_config_handler("snmpd",\1, \2, \3, \4);@p' >> $mibdir/mib_module_dot_conf.h
@@ -466,7 +466,7 @@ while test "x$new_module_list" != "x"; do
         #
         # check if $i has any errors, or warnings
         #
-        AH_TOP([#define config_error(x)])
+        AH_TOP([#define config_error(x) extern void this_function_is_not_used(void)])
         error=`$MODULECPP module_tmp_header.h | \
                $SED -n 's/.*config_error(\(.*\)).*/\1/p'`
 	if test "x$error" != "x"; then
@@ -479,7 +479,7 @@ while test "x$new_module_list" != "x"; do
       	# macro: config_warning(warning text)
       	#  - used to signal a configuration "warning" to be printed to the user
         #
-        AH_TOP([#define config_warning(x)])
+        AH_TOP([#define config_warning(x) extern void this_function_is_not_used(void)])
         warning=`$MODULECPP module_tmp_header.h | \
                  $SED -n 's/.*config_warning(\(.*\)).*/\1/p'`
 	if test "x$warning" != "x"; then
```

**Comment by nielsb** [comment]
That looks deable, please go ahead with it! I just want the warnings out og the way :-)

**Pull request closed without merging**
