### PR TITLE
-Add NETSNMP_OID_OUTPUT_FULL_AND_NUMERIC for -OF formatting of OIDs

### PR DESCRIPTION
**Pull request by rgumpertz68**
Add NETSNMP_OID_OUTPUT_FULL_AND_NUMERIC for -OF formatting of OIDs

This started with 567, 570, and 571.  Please use this one instead

### CODE REVIEW

**Comment by rgumpertz68** [comment]
OK, I deleted the whitespace changes just to make you happy.  Can we proceed now?

**Comment by rgumpertz68** [comment]
I'm not sure I understand what you want me to do now.  Are you accepting or rejecting the changes?  Are you asking me to merge the branch before accepting it?

**Comment by rgumpertz68** [comment]
I'm sorry. I misunderstood because you closed the request without commenting that you had pulled it.  Would it be that hard for you to add a comment to that effect?  A simple "pulled" would suffice...

**Comment by bvanassche** [comment]
A previous comment says "[bvanassche](https://github.com/bvanassche) closed this in https://github.com/net-snmp/net-snmp/commit/8815b2858c9b7c006e848683e68a09a9ab8b1b6f". From that commit:
```
libsnmp, apps: Add NETSNMP_OID_OUTPUT_FULL_AND_NUMERIC for -OF formatting of OIDs

Fixes: https://github.com/net-snmp/net-snmp/pull/572
Fixes: https://github.com/net-snmp/net-snmp/pull/567

[ bvanassche: edited commit message and patch formatting ]
```

Isn't that sufficient?

**Comment by rgumpertz68** [comment]
For some reason, I never received that comment.  I apologize.

                              Rick

**Pull request closed without merging**
