### PR TITLE
Handle SIGHUP for engine-id change

### PR DESCRIPTION
**Pull request by feroz-ahmed**
Handle SIGHUP cases for:
Modified engine-id doesnt work with SIGHUP, SNMP operations continue to work with old engine-id

### CODE REVIEW

**Comment by bvanassche** [comment]
Please fix the build failures.

**Comment by feroz-ahmed** [comment]
> Please fix the build failures.

ACK

**Comment by feroz-ahmed** [comment]
I'm facing few issues to build SNMP code on codespaces.

**Comment by bvanassche** [comment]
One of the regression tests fails. Please fix the regression test failure.

**Comment by feroz-ahmed** [comment]
So what is the next step, to get this commit merged?

**Comment by bvanassche** [comment]
Please combine the six commits into a single commit, e.g. as follows:
* Run `git pull --rebase` and fix the merge conflicts if there are any.
* Run `git rebase -i` and combine all the commits that should be combined.

**Pull request closed without merging**
